"use client";

import { useState } from "react";
import { Navbar } from "@/components/Navbar";
import { Container } from "@/components/Container";
import { SectionHeader } from "@/components/SectionHeader";
import { ProjectCard } from "@/components/ProjectCard";
import { ProjectsCarousel } from "@/components/ProjectsCarousel";
import { Footer } from "@/components/Footer";

const projects = [
  {
    title: "Restaurant Menu App",
    tagline: "Online menu with cart and order flow.",
    desc: "Interactive restaurant menu with categories, cart functionality, and order submission.",
    stack: ["HTML", "CSS", "JavaScript"],
    github:
      "https://github.com/marwoz01/TIN-Studia/blob/main/restaurant-app-main/README.md",
    demo: "https://your-demo-link.com/restaurant",
    image: "/projects/restaurant.jpg",
  },
  {
    title: "Twimba — Twitter Clone",
    tagline: "Post, like, retweet, comment.",
    desc: "Twitter-like app with posting, likes, retweets, and comments.",
    stack: ["HTML", "CSS", "JavaScript"],
    github:
      "https://github.com/marwoz01/Scrimba/tree/main/06%20-%20Twimba%2C%20Twitter%20Clone",
    demo: "https://your-demo-link.com/twimba",
    image: "/projects/twimba.jpg",
  },
  {
    title: "Color Scheme Generator",
    tagline: "Generate palettes from color and style.",
    desc: "Color palette generator using an external API, with HEX color codes.",
    stack: ["HTML", "CSS", "JavaScript", "API"],
    github:
      "https://github.com/marwoz01/Scrimba/tree/main/09%20-%20Color%20Scheme%20Generator",
    demo: "https://your-demo-link.com/colors",
    image: "/projects/colors.jpg",
  },
  {
    title: "Movie Watchlist (OMDb)",
    tagline: "Search movies and build your watchlist.",
    desc: "Movie search app using the OMDb API with a personal watchlist feature.",
    stack: ["HTML", "CSS", "JavaScript", "API"],
    github:
      "https://github.com/marwoz01/Scrimba/tree/main/09%20-%20Watch%20List",
    demo: "https://your-demo-link.com/movies",
    image: "/projects/movies.jpg",
  },
  {
    title: "Chef Claude",
    tagline: "AI-powered recipe suggestions.",
    desc: "Enter ingredients and get recipe suggestions generated by AI.",
    stack: ["React", "Vite", "API"],
    github: "https://github.com/marwoz01/chef-claude",
    demo: "https://your-demo-link.com/chef-claude",
    image: "/projects/chef.jpg",
  },
];

export default function Page() {
  const [expanded, setExpanded] = useState(false);
  const visibleProjects = expanded ? projects : projects.slice(0, 3);
  return (
    <>
      <Navbar />

      <main id="home">
        {/* HERO */}
        <section className="relative min-h-screen flex items-center">
          <Container>
            <div className="grid gap-10 md:grid-cols-12 md:items-end">
              <div className="md:col-span-8">
                <p className="text-xs uppercase tracking-[0.26em] text-white/50">
                  · Web Developer ·
                </p>

                <h1 className="mt-4 text-5xl sm:text-6xl md:text-7xl font-semibold tracking-tight leading-[0.95]">
                  Marcel Woźniak
                </h1>

                <p className="mt-6 max-w-2xl text-white/70 leading-relaxed">
                  Third-year Computer Science student focused on building
                  modern, performant web applications with React and Next.js.
                  Looking to grow as a Web Developer.
                </p>

                <div className="mt-8 flex flex-wrap gap-3">
                  <a
                    href="#projects"
                    className="rounded-full border border-white/15 bg-white/5 px-5 py-2 text-xs uppercase tracking-[0.18em] text-white/80 hover:bg-white/10"
                  >
                    View Projects
                  </a>
                  <a
                    href="#contact"
                    className="rounded-full border border-white/15 bg-white px-5 py-2 text-xs uppercase tracking-[0.18em] text-black hover:bg-white/90"
                  >
                    Contact
                  </a>
                </div>
              </div>

              <div className="md:col-span-4">
                <div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.04] backdrop-blur">
                  <img
                    src="/me.jpg"
                    alt="Marcel Woźniak"
                    className="h-full w-full object-cover opacity-90"
                  />
                </div>
              </div>
            </div>

            <div className="mt-14 h-px w-full bg-white/10" />
          </Container>
        </section>

        {/* ABOUT */}
        <section id="about" className="min-h-screen flex items-center">
          <Container>
            <SectionHeader
              kicker="About Me"
              title="Minimalist UI. Solid engineering."
              subtitle="I focus on frontend development, component architecture, accessibility, and performance."
            />

            <div className="grid gap-6 md:grid-cols-12">
              {/* PHOTO */}
              <div className="md:col-span-3 rounded-2xl border border-white/10 bg-white/[0.04] p-6 backdrop-blur">
                <p className="text-xs uppercase tracking-[0.26em] text-white/50">
                  Photo
                </p>

                <div className="mt-4 aspect-square w-full overflow-hidden rounded-2xl border border-white/10 bg-black/30">
                  <div className="flex h-full w-full items-center justify-center text-xs text-white/40">
                    Add photo (me.jpg)
                  </div>
                </div>

                <p className="mt-4 text-xs text-white/50 leading-relaxed">
                  Based in Gdańsk
                  <br />
                  Open to junior / intern roles
                </p>
              </div>

              {/* ABOUT TEXT */}
              <div className="md:col-span-5 rounded-2xl border border-white/10 bg-white/[0.04] p-6 backdrop-blur">
                <p className="text-xs uppercase tracking-[0.26em] text-white/50">
                  About
                </p>
                <p className="mt-4 text-sm leading-relaxed text-white/75">
                  I’m a third-year Computer Science student with a strong focus
                  on frontend development and modern web technologies. I work
                  with React and Next.js to build clean, responsive, and
                  user-friendly applications, and I have basic experience with
                  Node.js and Express on the backend. In addition, I’m expanding
                  my skills by learning WordPress and PHP, aiming to better
                  understand full-stack development and real-world web projects.
                </p>
              </div>

              {/* TECH STACK */}
              <div className="md:col-span-4 rounded-2xl border border-white/10 bg-white/[0.04] p-6 backdrop-blur">
                <p className="text-xs uppercase tracking-[0.26em] text-white/50">
                  Tech stack
                </p>

                <div className="mt-4 flex flex-wrap gap-2">
                  {[
                    "HTML",
                    "CSS",
                    "JavaScript",
                    "TypeScript",
                    "React",
                    "Next.js",
                    "Tailwind",
                    "LESS",
                    "SASS",
                    "Node.js (basics)",
                    "Express (basics)",
                    "WordPress (basics)",
                    "PHP (basics)",
                    "Git/GitHub",
                    "Figma",
                    "Canva",
                  ].map((t) => (
                    <span
                      key={t}
                      className="rounded-full border border-white/10 bg-black/30 px-3 py-1 text-xs text-white/75"
                    >
                      {t}
                    </span>
                  ))}
                </div>

                <div className="mt-5 h-px w-full bg-white/10" />
                <p className="mt-4 text-xs text-white/60">
                  GitHub:{" "}
                  <a
                    className="text-white/80 hover:text-white"
                    href="https://github.com/marwoz01"
                    target="_blank"
                    rel="noreferrer"
                  >
                    marwoz01
                  </a>
                </p>

                <p className="mt-2 text-xs text-white/60">
                  CV:
                  <a
                    className="ml-2 text-white/80 hover:text-white underline-offset-2 hover:underline"
                    href="/Marcel_Wozniak_CV_EN.pdf"
                    download
                  >
                    EN
                  </a>
                  <span className="mx-1 text-white/40">/</span>
                  <a
                    className="text-white/80 hover:text-white underline-offset-2 hover:underline"
                    href="/Marcel_Wozniak_CV_PL.pdf"
                    download
                  >
                    PL
                  </a>
                </p>
              </div>
            </div>
          </Container>
        </section>

        {/* PROJECTS */}
        <section id="projects" className="min-h-screen flex items-center">
          <Container>
            <SectionHeader
              kicker="Projects"
              title="Featured projects"
              subtitle="Selected builds with live demos and source code."
            />

            <ProjectsCarousel projects={projects} />
          </Container>
        </section>

        {/* CONTACT */}
        <section id="contact">
          <Container>
            <div className="grid gap-10 md:grid-cols-12">
              {/* LEFT */}
              <div className="md:col-span-5">
                <p className="text-xs uppercase tracking-[0.26em] text-white/50">
                  Contact
                </p>
                <h2 className="mt-4 text-4xl font-semibold leading-tight">
                  Get in touch
                </h2>

                <div className="mt-8 space-y-4 text-sm text-white/70">
                  <p>
                    Email:
                    <br />
                    <a
                      href="mailto:marwozniak01@gmail.com"
                      className="text-white hover:underline"
                    >
                      marwozniak01@gmail.com
                    </a>
                  </p>

                  <p>
                    Phone:
                    <br />
                    <a
                      href="tel:+48794121272"
                      className="text-white hover:underline"
                    >
                      +48 794 121 272
                    </a>
                  </p>

                  <p>
                    GitHub:
                    <br />
                    <a
                      href="https://github.com/marwoz01"
                      target="_blank"
                      rel="noreferrer"
                      className="text-white hover:underline"
                    >
                      github.com/marwoz01
                    </a>
                  </p>
                </div>
              </div>

              {/* RIGHT */}
              <div className="md:col-span-7 rounded-2xl border border-white/10 bg-white/[0.04] p-6 backdrop-blur">
                <p className="text-xs uppercase tracking-[0.26em] text-white/50">
                  Send message
                </p>

                <form className="mt-4 grid gap-3">
                  <input
                    className="h-11 rounded-xl border border-white/10 bg-black/40 px-4 text-sm outline-none placeholder:text-white/30 focus:border-white/25"
                    placeholder="Your name"
                  />
                  <input
                    className="h-11 rounded-xl border border-white/10 bg-black/40 px-4 text-sm outline-none placeholder:text-white/30 focus:border-white/25"
                    placeholder="Email"
                  />
                  <textarea
                    className="min-h-[120px] rounded-xl border border-white/10 bg-black/40 px-4 py-3 text-sm outline-none placeholder:text-white/30 focus:border-white/25"
                    placeholder="Message"
                  />
                  <button
                    type="button"
                    className="mt-2 h-11 rounded-xl bg-white text-xs uppercase tracking-[0.18em] text-black hover:bg-white/90"
                  >
                    Send message
                  </button>
                </form>
              </div>
            </div>
          </Container>
        </section>
      </main>

      <Footer />
    </>
  );
}
